trigger:
- master

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
    windows:
      imageName: 'windows-latest'

pool:
  vmImage: $(imageName)

steps: 
- script: dotnet build
  displayName: 'dotnet build'

- task: scope-for-dotnet@0
  displayName: Scope for .NET
  inputs:
    dsn: '$(SCOPE_DSN)'
